name: "Unit test"

runs:
  using: "composite"
  steps:
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
    - name: Set dummy token
      shell: bash
      run: echo API_TOKEN=\"\" > local.properties
    - name: Run test
      shell: bash
      run: ./gradlew test

