name: "Unit test"

runs:
  using: "composite"
  steps:
    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'
    - uses: gradle/actions/setup-gradle@v4
    - name: "Run test"
      shell: bash
      run: "gradlew test"